# Generated by Django 5.2 on 2025-04-04 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0004_parents_school_code_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='school',
            name='code',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='studentNumber',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
