# Generated by Django 5.2 on 2025-04-16 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0011_schoolaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schoolaccess',
            name='school_code',
        ),
    ]
