# Generated by Django 5.2 on 2025-04-17 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0014_levels_students_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='year',
        ),
        migrations.AddField(
            model_name='class',
            name='level',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gap.levels'),
            preserve_default=False,
        ),
    ]
