# Generated by Django 5.2 on 2025-04-18 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0017_alter_levels_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='levels',
            name='name',
            field=models.CharField(choices=[('Advanced ', 'Advanced '), ('Ordinary ', 'Ordinary ')], default='Advanced ', max_length=200),
        ),
    ]
