# Generated by Django 5.2 on 2025-04-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0018_alter_levels_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDisciplinemanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_descipline_marks', models.IntegerField(default=40)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gap.students')),
            ],
        ),
    ]
