# Generated by Django 5.2 on 2025-04-18 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0020_disciplinerecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('points_deducted', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('student_discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_history', to='gap.studentdisciplinemanagement')),
            ],
        ),
    ]
