# Generated by Django 5.2 on 2025-04-18 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0021_disciplinehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplinerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_history', to='gap.students'),
        ),
    ]
