# Generated by Django 5.2 on 2025-04-18 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0022_alter_disciplinerecord_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='disciplinerecord',
            old_name='recorded_by',
            new_name='recorded_by_name',
        ),
    ]
