# Generated by Django 5.2 on 2025-04-19 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0024_rename_recorded_by_name_disciplinerecord_recorded_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLibraryBookmanagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('book_Quantity', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.school')),
            ],
        ),
    ]
