# Generated by Django 5.2 on 2025-04-19 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0025_schoollibrarybookmanagement'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolLibraryBookRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rented_at', models.DateTimeField(auto_now_add=True)),
                ('returned', models.BooleanField(default=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='gap.schoollibrarybookmanagement')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gap.students')),
            ],
        ),
    ]
