# Generated by Django 5.2 on 2025-04-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0026_schoollibrarybookrental'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollibrarybookmanagement',
            name='book_rented',
            field=models.IntegerField(default=0),
        ),
    ]
