# Generated by Django 5.2 on 2025-04-19 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gap', '0027_schoollibrarybookmanagement_book_rented'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoollibrarybookrental',
            name='returned_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
